Fix UnicodeDecodeError when a required condition is empty in add form (#2173)
```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 371, in publish_module
  Module ZPublisher.WSGIPublisher, line 274, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module bika.lims.browser.analysisrequest.add2, line 72, in decorator
  Module bika.lims.browser.analysisrequest.add2, line 717, in __call__
  Module bika.lims.browser.analysisrequest.add2, line 1620, in ajax_submit
  Module zope.i18nmessageid.message, line 112, in __call__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 8: ordinal not in range(128)
```