Support for ReferenceWidget as a subfield (subform)
This commit resolves the following traceback:

```
2021-11-18 13:58:23,463 ERROR   [Zope.SiteErrorLog:252][waitress-0] 1637240303.460.260551223611 http://localhost:9090/senaite/bika_setup/astbreakpoints/breakpointstable-2/@@edit
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 371, in publish_module
  Module ZPublisher.WSGIPublisher, line 274, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module plone.z3cform.layout, line 63, in __call__
  Module plone.z3cform.layout, line 57, in update
  Module z3c.form.form, line 162, in render
  Module zope.browserpage.viewpagetemplatefile, line 49, in __call__
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 378, in __call__
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 302, in render
  Module chameleon.template, line 192, in render
  Module 7439b2cdb2e5b093912e19beb0c9e79e, line 115, in render
  Module 1fc13e73925ac7ac7d312158279a54ca, line 2201, in render_titlelessform
  Module 1fc13e73925ac7ac7d312158279a54ca, line 424, in render_fields
  Module 1fc13e73925ac7ac7d312158279a54ca, line 150, in render_widget_rendering
  Module 1fc13e73925ac7ac7d312158279a54ca, line 1022, in render_field
  Module zope.tales.expressions, line 250, in __call__
  Module Products.PageTemplates.Expressions, line 225, in _eval
  Module Products.PageTemplates.Expressions, line 155, in render
  Module zope.browserpage.simpleviewclass, line 41, in __call__
  Module zope.browserpage.viewpagetemplatefile, line 81, in __call__
  Module zope.browserpage.viewpagetemplatefile, line 49, in __call__
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 378, in __call__
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 302, in render
  Module chameleon.template, line 192, in render
  Module 0d3a9da64b3443b8ffaff79385eb319f, line 586, in render
  Module 0d3a9da64b3443b8ffaff79385eb319f, line 456, in render_widget_wrapper
  Module zope.tales.expressions, line 250, in __call__
  Module Products.PageTemplates.Expressions, line 225, in _eval
  Module Products.PageTemplates.Expressions, line 155, in render
  Module z3c.form.widget, line 154, in render
  Module zope.browserpage.viewpagetemplatefile, line 49, in __call__
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 378, in __call__
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 302, in render
  Module chameleon.template, line 192, in render
  Module 4268acf8d9718e5167027debbb8128a8, line 646, in render
  Module 4268acf8d9718e5167027debbb8128a8, line 128, in render_widget_row
  Module zope.tales.expressions, line 250, in __call__
  Module Products.PageTemplates.Expressions, line 225, in _eval
  Module Products.PageTemplates.Expressions, line 155, in render
  Module collective.z3cform.datagridfield.datagridfield, line 324, in render
  Module z3c.form.object, line 310, in render
  Module z3c.form.widget, line 154, in render
  Module zope.browserpage.viewpagetemplatefile, line 49, in __call__
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 378, in __call__
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 302, in render
  Module chameleon.template, line 192, in render
  Module c23892e4e47067c01762be611958315a, line 172, in render
  Module zope.tales.expressions, line 250, in __call__
  Module Products.PageTemplates.Expressions, line 225, in _eval
  Module Products.PageTemplates.Expressions, line 155, in render
  Module z3c.form.widget, line 154, in render
  Module zope.browserpage.viewpagetemplatefile, line 49, in __call__
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 378, in __call__
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 302, in render
  Module chameleon.template, line 215, in render
  Module chameleon.template, line 192, in render
  Module c76fe6a1ae4bbf31390ce35f520882ac, line 117, in render
  Module zope.tales.pythonexpr, line 73, in __call__
   - __traceback_info__: (view.get_input_widget_attributes())
  Module <string>, line 1, in <module>
  Module senaite.core.z3cform.widgets.uidreference, line 173, in get_input_widget_attributes
  Module senaite.core.z3cform.widgets.uidreference, line 148, in get_catalog
  Module senaite.core.z3cform.widgets.uidreference, line 113, in attr
  Module senaite.core.z3cform.widgets.uidreference, line 97, in get_context
  Module bika.lims.api, line 328, in get_portal_type
  Module bika.lims.api, line 203, in fail
APIError: {'disk_content': 23, 'antibiotic': '6815e43a2c184cf681fc86f147a8b09f', 'diameter_r': 12, 'microorganism': '915956ce9386479bab9b8a7d2f0e4c7c', 'diameter_s': 12} is not supported.
```

Basically, when the uidreferencewidget is used as a subfield, the form on submission
is actually a subform that stores the value for the current field as the context
instead of the object being edited or added.

This commit checks if the current is a subForm and if so, it uses the parentForm to
retrieve the correct context and portal_type

```python
> /home/jordi/dev/zinstance/src/senaite.core/src/senaite/core/z3cform/widgets/uidreference.py(97)

  81         def get_context(self):
  82             """Get the current context
  83
  84             NOTE: If we are in the ++add++ form, `self.context` is the container!
  85                   Therefore, we create one here to have access to the methods.
  86             """
  87             schema_iface = self.field.interface
  88             if schema_iface and schema_iface.providedBy(self.context):
  89                 return self.context
  90
  91             # Hack alert!
  92             # we are in ++add++ form and have no context!
  93             # Create a temporary object to be able to access class methods
  94             form = self.get_form()
  95             portal_type = getattr(form, "portal_type", None)
  96             import pdb;pdb.set_trace()
  97  ->         if not portal_type:
  98                 portal_type = api.get_portal_type(self.context)
  99             portal_types = api.get_tool("portal_types")
 100             fti = portal_types[portal_type]
 101             factory = getUtility(IFactory, fti.factory)
 102             context = factory("temporary")
 103             # hook into acquisition chain
 104             context = context.__of__(self.context)
 105             return context

 (Pdb++) form
<collective.z3cform.datagridfield.datagridfield.DataGridFieldObjectSubForm object at 0x7fe79ad19b90>
(Pdb++) self.context
{'disk_content': 23, 'antibiotic': '6815e43a2c184cf681fc86f147a8b09f', 'diameter_r': 12, 'microorganism': '915956ce9386479bab9b8a7d2f0e4c7c', 'diameter_s': 12}
(Pdb++) portal_type
(Pdb++) IDescriptiveGroup.providedBy(form)
False
(Pdb++) form.context
{'disk_content': 23, 'antibiotic': '6815e43a2c184cf681fc86f147a8b09f', 'diameter_r': 12, 'microorganism': '915956ce9386479bab9b8a7d2f0e4c7c', 'diameter_s': 12}
(Pdb++) parent = form.parentForm
(Pdb++) parent.context
<BreakpointsTable at /senaite/bika_setup/astbreakpoints/breakpointstable-2>
(Pdb++) form.portal_type
*** AttributeError: 'DataGridFieldObjectSubForm' object has no attribute 'portal_type'
(Pdb++) from z3c.form.interfaces import ISubForm
(Pdb++) ISubForm.providedBy(form)
True
(Pdb++) ISubForm.providedBy(parent)
False

```