Fix missing closing tags while generating pot
Traceback (most recent call last):
  File "/home/jordi/Desenvolupament/plone5/buildout-cache/eggs/i18ndude-5.3.4-py2.7.egg/i18ndude/extract.py", line 543, in tal_strings
    parser.parseFile(filename)
  File "/home/jordi/Desenvolupament/plone5/buildout-cache/eggs/zope.tal-4.4-py2.7.egg/zope/tal/htmltalparser.py", line 166, in parseFile
    self.parseString(data)
  File "/home/jordi/Desenvolupament/plone5/buildout-cache/eggs/zope.tal-4.4-py2.7.egg/zope/tal/htmltalparser.py", line 173, in parseString
    self.feed(data)
  File "/home/jordi/Desenvolupament/plone5/Python-2.7/lib/python2.7/HTMLParser.py", line 117, in feed
    self.goahead(0)
  File "/home/jordi/Desenvolupament/plone5/Python-2.7/lib/python2.7/HTMLParser.py", line 163, in goahead
    k = self.parse_endtag(i)
  File "/home/jordi/Desenvolupament/plone5/Python-2.7/lib/python2.7/HTMLParser.py", line 401, in parse_endtag
    self.handle_endtag(elem)
  File "/home/jordi/Desenvolupament/plone5/buildout-cache/eggs/zope.tal-4.4-py2.7.egg/zope/tal/htmltalparser.py", line 233, in handle_endtag
    self.close_enclosed_tags(tag)
  File "/home/jordi/Desenvolupament/plone5/buildout-cache/eggs/zope.tal-4.4-py2.7.egg/zope/tal/htmltalparser.py", line 267, in close_enclosed_tags
    self.implied_endtag(self.tagstack[-1], 1)
  File "/home/jordi/Desenvolupament/plone5/buildout-cache/eggs/zope.tal-4.4-py2.7.egg/zope/tal/htmltalparser.py", line 281, in implied_endtag
    position=self.getpos())
  File "/home/jordi/Desenvolupament/plone5/buildout-cache/eggs/zope.tal-4.4-py2.7.egg/zope/tal/talgenerator.py", line 773, in emitEndElement
    (what, name, name), self.position)
TALError: TAL attributes on <span> require explicit </span>, at line 58, column 27, in file src/senaite.core/src/senaite/core/browser/samples/templates/dispatch_samples.pt