Fix traceback in analyses listing from ARTemplate view
```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module senaite.core.listing.view, line 214, in __call__
  Module senaite.core.listing.ajax, line 103, in handle_subpath
  Module senaite.core.listing.decorators, line 63, in wrapper
  Module senaite.core.listing.decorators, line 50, in wrapper
  Module senaite.core.listing.decorators, line 100, in wrapper
  Module senaite.core.listing.ajax, line 528, in ajax_folderitems
  Module senaite.core.listing.decorators, line 88, in wrapper
  Module senaite.core.listing.ajax, line 307, in get_folderitems
  Module bika.lims.browser.widgets.artemplateanalyseswidget, line 200, in
folderitems
  Module senaite.core.listing.view, line 895, in folderitems
  Module bika.lims.browser.widgets.artemplateanalyseswidget, line 233, in
folderitem
KeyError: 'required'
```