Global Permission and Role Mappings refactoring (#1237)
* Introduced global rolemap configuration

* Use global rolemap for sample_received

* Use `acquire="False"` in global rolemap and revoke permissions for critical fields

* Registered permission "Reject Analysis Request"

* Added default roles to generic permissions

* Refactored `sample_received` state to use global permission to roles mapping

* Changed title of Workflow

* Set permissions for sample_registered

* Updated rolemap

* Comments and sorting

* Use global roles for sample_registered state

* Updated until sample_due state

* Added sample_received state

* Added attachment_due state

* Added to_be_preserved state

* Added to_be_verified state

* Added verified state

* Added published state

* Added rejected state

* Added invalid state

* Cancelled state added

* Added states and variables

* fixed comment

* Rolemap updated

* Make some fields readonly in sample_due state

* Make some fields readonly in sample_received state

* Make some fields readonly

* Make some fields readonly in verified/published

* Make fields readonly in invalid states

* Manage "Retract" Permission as well

* Make date received field uneditable in states before sample_received

* Allow to change the publication specification in state verified/published

* Keep date received field readonly

* Keep date received editable in sample_due state

* Manage Access Contents Information permission as well

* Removed duplicate states

* Force rolemappings of Analysis Requests in upgrade step

Since this PR changes the permissions schema, as well as the
rolemap.xml, there is the need to update the rolemappings for all
objects affected (Analysis Requests)

* Run rolemap step in upgrade 1.3

* Updated rolemappings

* Allow to change the results interpretation in verified state

* Sample can only be cancelled if is in an open state

* Remove "BIKA: Edit AR" permission. No longer used

* Results cannot be editable in `to_be_verified` status

* "Edit Results". Granted from "received" onwards until "to_be_verified"

* Some more sticky notes

* "BIKA: Preserve Sample" -> "Transition: Preserve Sample"

This permission is not used anywhere but for the "preserve" transition
as a permission guard. Not used in views, and workflow definitions
other than ar_workflow

I change the name following the same criteria we established with
Field-specific permissions with the aim to keep permissions
understandable.

* BIKA: Publish --> Transition: Publish Results

* Remove "Publish" permission from setup_handlers

* BIKA: Receive Sample --> Transition: Receive Sample

* BIKA: Retract --> Transition: Retract

* BIKA: Sample Sample --> Transition: Sample Sample

* BIKA: Schedule Sampling --> Transition: Schedule Sampling

* BIKA: Verify --> Transition: Verify

* Reject Analysis Request --> Transition: Reject Sample

* Start redefinition of permissions

* Some comments

* Added permission RejectSample to permissions

* Field: Edit ? --> senaite.core: Field: Edit ?

* Mapping of Permissions in AnalysisRequest type

* Added analysis' field permissions in permissions.py

* Mapping of Analysis' Field permissions

* Transition: ? --> senaite.core: Transition: ?

* Permissions mappings in code

* BIKA: Add ? --> senaite.core: Add ?

* FieldEditHidden --> FieldEditAnalysisHidden

* Changes for AddAnalysis permission in ar_workflow

* FieldEditRemarks --> FieldEditAnalysisRemarks

* Fix Transition permissions in ar_workflow

Transition permissions must be in line with exit-transitions. Otherwise,
it might be confusing when looking at the permissions schema in ZMI

* Field Edit Hidden --> Field Edit Analysis Hidden

* Fix API_Security doctest

* Cleanup "Transition: Verify" from ar_workflow and add "Invalidate"

"Transition: Verify" only applies to analysis workflow, not to AR
workflow. The reason is that verify transition takes place automatically
as soon as the transition "verify" is done against all individual analyses
the AR contains. Thus, the transition "verify" from AR ultimately relies
on the guard and premissions set for "verify" in analysis_workflow.xml

On the other hand, permission guard for invalidate transition was mixed
with the permission for retraction. Retraction and invalidation are two
different things.

* Some comments in transitions and preservation inconsistencies

Transitions and statuses related with preservation are inconsistent.

* Consider to add "Transition: Add Partition" permission

The transition create_partition relies now on "Edit Results", that
is a different thing from creating partitions.

* Remove "Owner" from rolemap.xml (for now, AR)

* Refactoring of basic workflows and permissions (first iteration)

* Workflow cleanup (iteration 2)

* Drop cancellation_workflow and invalidation_workflow (iteration 3)

* remove cancellation_state and inactive_state in favour of is_active

* Fix API doctest and bind "BikaSetup" to "senaite_setup_workflow"

* Fixed permissions for Setup, Laboratory and LabContact types

* No need of a "View Setup" permission

* Fix permissions for Client and Client contacts

* Fix permissions for instruments

* Fix permissions for methods

* Fix permissions for Analysis services

* Remove AllowClerksToEditClients option from setup

By default, clients can be modified by LabClerks as per the
permissions settings from `senaite_client_workflow`.

The proper way to prevent LabClerks from editing Clients is by
doing any of the options below:

- Apply permissions changes in `senaite_client_workflow`. Either
  in the xml directly or through ZMI > portal_workflow

- Bind Client type to a custom workflow

* Cleanup setupGroupsAndRoles from setuphandler

* remove AddARAttachment and DelARAttachment from AR type

* Fix test ARAnalysesField

* Bad import

* Fix Listings.rst test

* Remove cancellation_state and invalid_state indexes

* isBasicTransitionAllowed cleanup

* Fix API doctest

* Fix API.rst (again)

* Remove "BIKA: Manage Clients" permission

Substitute: "Modify Portal Contents" for clients folder

* Remove "BIKA: Manage Suppliers" permission

Use default "View" or "Modify Portal Content" permissions for suppliers folder instead

* Remove "BIKA: Expire Sample" permission

* Remove "BIKA: Dispose Sample" permission

* Remove "BIKA: Import Analysis" permission

* Remove "BIKA: Edit Sample" permission

* Remove "BIKA: Edit Client" permission

* Remove "BIKA: Manage Supply Orders" permission

* Remove "BIKA: Edit Batch" permission

Use "Modify Portal Content" instead

* Added senaite_invoices_workflow

* Remove manual assignment of "Delete objects" for AR

ar_workflow already takes care of this permission already,
so there is no need of a manual assignment of this permission
each time an AR is modified.

* changeWorkflowState cleanup

* Added `senaite_worksheets_workflow` (for worksheets folder)

* Remove bikasetup's objectmodified handler

* Fix changeWorkflowState (argh!)

* Grant "Delete objects" permission in some AR statuses

* Added `senaite_referencesamples_workflow` for ReferenceSampleFolder

* Added `senaite_reports_workflow`

Do not allow access to Administrative+Productivity reports to users
other than lab personnel.

* Permission "Transition: Dispatch Order"

* Permissions: "Transition: Close" + "Transition: Reopen"

* Remove "BIKA: Cancel and Reinstate" permission

Use "Transition: Cancel" and "Transition: Reinstate" permissions instead

* permissions.py + permissions.zcml review

* Remove setupPermissions and sorted out permissions.zcml

* Changed IDs to senaite.core.permissions.*

* Fix __init__.py re Add Permission

* Changed ID prefixes to `senaite.core.permissions`

* Added upgrade steps

* Changed "BIKA:" prefix in permissions to "senaite.core:"

* Remove profile imports

* Remove redundant `is_active` indexes in catalogs

`is_active` index is already present in `catalog_base_template`

* Upgrade step upgrade

* Upgrade version info at the end of the process

* Recursive Update Role Mappings

* Fixed upgrade step

* cancelled --> state_id

* Added logger line

* Added custom recursiveUpdateRoleMappings to upgrade utils

* Apply commit transaction at given intervals

* Typo

* My last attempt

* Log when the number of processed objects for each run is >= 100

* Added Changelog

* Client cannot create ARs

* Removed trailing whitespaces

* LabClerk: Insufficient privileges for Sample Types listing

* Added "Add SampleType" permission

* Added "Add AnalysisCategory" permission

* Harmonize type views

Since there are users that can have View permission for a given type but
not Modify portal content permission, the default view for types (at least
inside setup) should be base_view. Otherwise, if the user has View
permission, but not Modify portal content permission, an Insufficient
Privileges error is displayed, without other information. So, the user
cannot see the contents of the type unless he/she types /view or /base_view
at the end of the url

* Added missing "Add" permissions

* Allow LabClerk to Add and modify setup items (e.g. SampleTypes)

* Use field permission to edit results interpretation

* Give field edit permissions to LabClerk for SampleType and SamplePoint

Otherwise, labclerk won't be able to create new ARs

* Added field permission for remarks

* Fix Traceback on setup edit

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerPageTemplate, line 91, in __call__
  Module Products.CMFFormController.BaseControllerPageTemplate, line 29, in _call
  Module Products.CMFFormController.ControllerBase, line 232, in getNext
  Module Products.CMFFormController.Actions.TraverseTo, line 38, in __call__
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerPythonScript, line 107, in __call__
  Module Products.CMFFormController.ControllerBase, line 232, in getNext
  Module Products.CMFFormController.Actions.TraverseTo, line 38, in __call__
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerPythonScript, line 107, in __call__
  Module Products.CMFFormController.ControllerBase, line 232, in getNext
  Module Products.CMFFormController.Actions.TraverseTo, line 38, in __call__
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerPythonScript, line 107, in __call__
  Module Products.CMFFormController.ControllerBase, line 232, in getNext
  Module Products.CMFFormController.Actions.RedirectToAction, line 44, in __call__
ValueError: No view action found for bika_setup

* Traceback on Batch creation

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.FactoryTool, line 478, in __call__
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerPageTemplate, line 91, in __call__
  Module Products.CMFFormController.BaseControllerPageTemplate, line 29, in _call
  Module Products.CMFFormController.ControllerBase, line 232, in getNext
  Module Products.CMFFormController.Actions.TraverseTo, line 38, in __call__
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerPythonScript, line 107, in __call__
  Module Products.CMFFormController.ControllerBase, line 232, in getNext
  Module Products.CMFFormController.Actions.TraverseTo, line 38, in __call__
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerPythonScript, line 107, in __call__
  Module Products.CMFFormController.ControllerBase, line 232, in getNext
  Module Products.CMFFormController.Actions.TraverseTo, line 38, in __call__
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerPythonScript, line 107, in __call__
  Module Products.CMFFormController.ControllerBase, line 232, in getNext
  Module Products.CMFFormController.Actions.RedirectToAction, line 44, in __call__
ValueError: No view action found for B-001

* Insufficient privileges for Client in base samples folder

* Fix tests