Fixed error regards to field_icons attribute access from bika_listing_table Error trace: URL: /xxx/zinstance/src/bika.lims/bika/lims/browser/templates/bika_listing_table.pt Line 525, Column 5 Expression: <PythonExpr (view.bika_listing.field_icons.get(uid, []))> AttributeError: 'XXXView' object has no attribute 'field_icons'
Conflicts:
	bika/lims/browser/templates/bika_listing_table.pt