Avoid parse errors for ZCTextIndex
Traceback (innermost last):
  Module ZServer.ZPublisher.Publish, line 144, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZServer.ZPublisher.Publish, line 44, in call_object
  Module senaite.app.listing.view, line 216, in __call__
  Module senaite.app.listing.ajax, line 109, in handle_subpath
  Module senaite.core.decorators, line 20, in decorator
  Module senaite.app.listing.decorators, line 63, in wrapper
  Module senaite.app.listing.decorators, line 50, in wrapper
  Module senaite.app.listing.decorators, line 100, in wrapper
  Module senaite.app.listing.ajax, line 432, in ajax_folderitems
  Module senaite.app.listing.decorators, line 88, in wrapper
  Module senaite.app.listing.ajax, line 313, in get_folderitems
  Module senaite.app.listing.view, line 901, in folderitems
  Module senaite.app.listing.view, line 715, in _fetch_brains
  Module senaite.app.listing.view, line 781, in search
  Module senaite.app.listing.view, line 708, in text_index_search
  Module Products.CMFPlone.CatalogTool, line 463, in searchResults
  Module Products.ZCatalog.ZCatalog, line 625, in searchResults
  Module Products.ZCatalog.Catalog, line 1091, in searchResults
  Module Products.ZCatalog.Catalog, line 634, in search
  Module Products.ZCatalog.Catalog, line 564, in _search_index
  Module Products.ZCTextIndex.ZCTextIndex, line 209, in query_index
  Module Products.ZCTextIndex.QueryParser, line 153, in parseQuery
  Module Products.ZCTextIndex.QueryParser, line 193, in _parseOrExpr
  Module Products.ZCTextIndex.QueryParser, line 211, in _parseAndExpr
  Module Products.ZCTextIndex.QueryParser, line 233, in _parseNotExpr
  Module Products.ZCTextIndex.QueryParser, line 241, in _parseTerm
  Module Products.ZCTextIndex.QueryParser, line 260, in _parseAtom
  Module Products.ZCTextIndex.QueryParser, line 188, in _get
  Module Products.ZCTextIndex.QueryParser, line 174, in _require
ParseError: Token <Token:ATOM> required, u'OR' found