Add support for dates before 1900 (#2090)
* Catch ValueError in datetimewidget

Traceback:
```
Traceback (innermost last):
  Module ZServer.ZPublisher.Publish, line 144, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZServer.ZPublisher.Publish, line 44, in call_object
  Module bika.lims.browser.analysisrequest.view, line 42, in __call__
  Module bika.lims.browser.header_table, line 99, in __call__
  Module Products.Five.browser.pagetemplatefile, line 126, in __call__
  Module Products.Five.browser.pagetemplatefile, line 61, in __call__
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 378, in __call__
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 302, in render
  Module chameleon.template, line 215, in render
  Module chameleon.template, line 192, in render
  Module b5af7af227d0614ddb683e49ef7fbcf2, line 576, in render
  Module f84d498475cc404181368cde9fa956bc, line 379, in render_edit
  Module d88bffbebbf4e01f15a333556ab23c2e, line 702, in render_edit
  Module f84d498475cc404181368cde9fa956bc, line 323, in __fill_widget_body
  Module zope.tales.pythonexpr, line 73, in __call__
   - __traceback_info__: (widget.get_time(value) if value else '')
  Module <string>, line 1, in <module>
  Module senaite.core.browser.widgets.datetimewidget, line 88, in get_time
  Module DateTime.DateTime, line 1566, in strftime
ValueError: year=1111 is before 1900; the datetime strftime() methods require year >= 1900
```

* Handle dates before 1900 gracefully in dtime API

* Support date before 1900 in DX datewidget

* Support date before 1900 in searchable text tokens

* Support dates < 1900 in samples view

* Moved to_localized_time to date API

* Pad a zero if value is a single digit

* Changelog updated

* Fix tests and added some more

* Make flake8 happy

* Removed unused imports

* Ensure DateTime object when a string was passed in

Co-authored-by: Jordi Puiggené <jp@naralabs.com>