Better handling of RemarksField and friendly display (#1495)
* Make RemarksField to store historic records in json format

* Better styling of the Remarks widget

* Fix get_include_methods function from jsonapi

When include_methods param is used in a read call with a single
parameter (instead of a list of more than one), the jsonapi does
not handle the value parameter properly and transforms it to
a list of characters instead.

A call like follows:

```
this.ajax_submit({
  url: this.get_portal_url() + "/@@API/read",
  data: {
          catalog_name: "uid_catalog",
          UID: widget.attr('data-uid'),
          include_methods: ["getSomething"],
        }
}).done(function(data) {
  return deferred.resolveWith(this, [data.objects[0]["getSomething"]]);
});
```

fails. The function `get_include_methods` returns `getSomething`
instead of a list `[getSomething]`. Therefore, the function
`load_method_values` tries the following calls to the instance:
`g`, `e`, `t`, `S`, `o`, ...

If the call is like follows:
```
this.ajax_submit({
  url: this.get_portal_url() + "/@@API/read",
  data: {
          catalog_name: "uid_catalog",
          UID: widget.attr('data-uid'),
          include_methods: ["getSomething", "getId"],
        }
}).done(function(data) {
  return deferred.resolveWith(this, [data.objects[0]["getSomething"]]);
});
```
the list is resolved properly.

* Now we are here, make it a bit better

* Changelog

* Don't use json.dumps, rather handle records with RemarksHistory

* Handle legacy values in an easier way

* Optimize imports

* Changelog

* support for markdown in Remarks

* Remove datetime formatting

* Fix MarkdownException: UnicodeDecodeError: Markdown only accepts unicode or ascii input

* Convert plain list to RemarksHistoryRecord

* Add "record" class to the container of a remarks history entry

* Remove "well" container from manage results in WS and Sample

* Move css to remarkswidget.css

* fix bad indentation

* Show remarks in overlay of worksheets

* Do not display record-header when no user_id

This makes the record-header to not be displayed for legacy entries

* ulocalized creation time

* Fix AttributeError: 'super' object has no attribute '__eq__'

* Whitespace only

* imports sorted

* Avoid empty remarks submission

* Parse legacy remarks

* Sort remarks with the newest first

* Emit Event for new remarks

* Check for valid input before activating the button

* Changed CSS Styles for Readonly Remarks Widget

* Changed variable name

* Fixed overlay for worksheets

* Code restructuring

* Code formatting only

* Fix the legacy parsing to handle newlines in the content

* Comment only

* Reindex object after remarks set

* Removed markdown rendering from remarks

* Pin Pillow for Scrutinizer

* Pinned more versions for Scrutinizer

* Replace RemarksWidget by TextAreaWidget for setup content types

* Make add-button blue

Co-authored-by: Ramon Bartl <rb@ridingbytes.com>