Analyses view refactoring (#604)
* First redux+refactoring of analyses.py

* Return False if permission=None in analyses.has_permission

* Analysis editable if not submitted, regardless of point of capture

One of the conditions for analysis to be edited is that a result mustn't
be submitted already. This check was done when the point of capture is
"field" (the result can be set when the sample is collected), but this
condition was not checked if the point of capture is "lab" (the result
must be set in the lab, after the sample is received).

* is_analysis_edition_allowed to be removed by DCWorkflow submit guard

* Clarifying comment in is_analysis_valid

If an analysis is a ReferenceAnalysis, there is no need to check if
the assigned instrument is valid when evaluating if is editable,
cause by default, ReferenceAnalysis are used as a mechanism to promote
an Instrument to a valid state if the result entered is inside the
valid range.

* Redux browser.analyses.get_analysis.spec

* Redux browser.analyses._folder_item_css_class

* Redux browser.analyses._folder_item_duedate

* Review browser.analyses._folder_item_result

* Review browser.analyses._folder_item_calculation

* Review browser.analyses._folder_item_verify_icons function

* Add icon/anchor to worksheet for assigned analyses

* Added browser.analyses._folder_item_reflex_icon

* Added get_image function in utils

* Let get_image resolve the portal_url

* Make get_image to resolve ++resources/bika.lims

* Replace img generation slugs by get_image

* Reduce complexity in _folder_item_reflex_icons

* Add _folder_report_visibility

* Remove whitespaces

* Move _folder_items_* functions to the end of the class

* Comments for _append_after_element and _get_object

* Detection Limit selector wrongly displayed

* Title for image element was not rendered

* Add 'state-<review_sate>' and 'type-<portal_type>' in row_class

* get_image replacement in _folder_item_duedate

* remove title param from get_image

* Optimization of methods vocabulary

* Remove get_methods_brains (complexity redux)

* Complexity redux get_methods_vocabulary

* get_methods_vocabulary, rename param analysis to analysis_brain

* Cleanup get_instrument_vocabulary()

* Remove unnecessary code

* Added _folder_item_category

* Comment for _folder_item_instrument

* Snippets before/after uncertainty are not displayed

* Traceback on submission (interims not found)

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.analysisrequest.workflow, line 61, in __call__
  Module bika.lims.browser.analysisrequest.workflow, line 392, in workflow_action_submit
KeyError: 'a8cef13a4c484da78d85c817b5993e4e'

* Hide verification additional info for retracted analyses

* Remove warnings

* PEP8

* Remove unnecessary translation and bad warning

Omit the assignment to the attribute title in anchors when the
instrument entry of results is not allowed.
Also, fix the following warning:

WARNING Bika Instrument entry of results not allowed for
${service} couldn't be translated

* Changelog AnalysesView code refactoring

* Changelog update for #621

* memmoize has_permission in AnalysesView

* memoize is_analysis_edition_allowed in AnalysesView

* memoize get_instrument from AnalysesView

* Added memoized get_object_by_uid in AnalysesView

* redux get_instrument in AnalysesView

* Redux is_analysis_instrument_valid in AnalysesView

* Redux is_analysis_edition_allowed in AnalysesView

* Cleanup whitespace lines in has_permission from AnalysesView

* Add get_object and remove get_object_by_uid in AnalysesView

* Force instrument retrieval by uid so it will be cached

* Redux get_methods_vocabulary

* Fix get_instruments_vocabulary (portal-type -> portal_type)

* Use 'bika_setup_catalog' for methods searches

* memoize getAnalysts in AnalysesView

* Remove _objects_map and use self.get_object instead of self._get_object

* Remove self._methods_map in AnalysesView

* Added temporary counter to keep track of number of calls

* Initialize _count_calls in __init__

* Return item with no values when Analysis has no methods assigned

* Better formatting

* Some formatting

* Add before_render and load_analysis_categories functions

* Move is edition allowed for current user to before_render

* Simplify multi-verification check

* Initialize decimal mark var in the constructor

* Better use context in constructor rather than self.context

* can_edit_analyses -> self.allow_edit

* Added folder_item_dry_matter function

* Organize imports

* Clean-up and redux

* Remove unused imports

* Reorganize functions order

* getAnalysts -> get_analysts

* Force before_render call in folder_items()

* Remove count_calls

* Imports reordered and resolved * imports

* Corrected API call to retrieve the object by UID

* Reverted, sorry

* PEP8 only

* Docstrings only

* minor refactoring