ReferenceAnalysis workflow does not have unassigned state (#1121)
Fixes the following Traceback:

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.GenericSetup.tool, line 1053, in manage_doUpgrades
  Module Products.GenericSetup.upgrade, line 166, in doStep
  Module bika.lims.upgrade, line 55, in wrap_func_args
  Module bika.lims.upgrade.v01_03_000, line 101, in upgrade
  Module bika.lims.upgrade.v01_03_000, line 431, in update_workflows
  Module bika.lims.upgrade.v01_03_000, line 668, in get_role_mappings_candidates
  Module bika.lims.upgrade.v01_03_000, line 749, in get_rm_candidates_for_referenceanalysisworkflow
AttributeError: unassigned