Fix issues with new UID reference field for dexterity types (#1873)
* Fix AttributeError "SimpleViewClass from ...has no attribute 'portal_type'"

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 371, in publish_module
  Module ZPublisher.WSGIPublisher, line 274, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module plone.autoform.view, line 42, in __call__
  Module plone.autoform.view, line 33, in render
  Module Products.Five.browser.pagetemplatefile, line 126, in __call__
  Module Products.Five.browser.pagetemplatefile, line 61, in __call__
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 378, in __call__
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 302, in render
  Module chameleon.template, line 192, in render
  Module 346cb68a0f0844429cacfbe2e98d87b8, line 419, in render
  Module cda2dbd14c33e8ec246aff05da1e55bc, line 1449, in render_master
  Module cda2dbd14c33e8ec246aff05da1e55bc, line 407, in render_content
  Module 346cb68a0f0844429cacfbe2e98d87b8, line 404, in __fill_content_core
  Module 346cb68a0f0844429cacfbe2e98d87b8, line 150, in render_content_core
  Module zope.tales.expressions, line 250, in __call__
  Module Products.PageTemplates.Expressions, line 225, in _eval
  Module Products.PageTemplates.Expressions, line 155, in render
  Module zope.browserpage.simpleviewclass, line 41, in __call__
  Module zope.browserpage.viewpagetemplatefile, line 81, in __call__
  Module zope.browserpage.viewpagetemplatefile, line 49, in __call__
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 378, in __call__
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 302, in render
  Module chameleon.template, line 192, in render
  Module 0d3a9da64b3443b8ffaff79385eb319f, line 586, in render
  Module 0d3a9da64b3443b8ffaff79385eb319f, line 456, in render_widget_wrapper
  Module zope.tales.expressions, line 250, in __call__
  Module Products.PageTemplates.Expressions, line 225, in _eval
  Module Products.PageTemplates.Expressions, line 155, in render
  Module z3c.form.widget, line 154, in render
  Module zope.browserpage.viewpagetemplatefile, line 49, in __call__
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 378, in __call__
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 302, in render
  Module chameleon.template, line 215, in render
  Module chameleon.template, line 192, in render
  Module ae5ff69a75b8cded49f12b36f1427872, line 152, in render
  Module zope.tales.pythonexpr, line 73, in __call__
   - __traceback_info__: (view.render_reference(uid))
  Module <string>, line 1, in <module>
  Module senaite.core.z3cform.widgets.uidreference, line 198, in render_reference
  Module senaite.core.z3cform.widgets.uidreference, line 143, in get_display_template
  Module senaite.core.z3cform.widgets.uidreference, line 111, in attr
  Module senaite.core.z3cform.widgets.uidreference, line 95, in get_context
AttributeError: 'SimpleViewClass from /home/jordi/Desenvolupament/p' object has no attribute 'portal_type'
```

* Fix Traceback when removing the selected value for an UIDReferenceField

```
2021-11-10 10:33:14,222 ERROR   [Zope.SiteErrorLog:252][waitress-0] 1636536794.220.25843379875 http://localhost:9090/senaite/bika_setup/astpanels/astpanel-2/@@edit
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 371, in publish_module
  Module ZPublisher.WSGIPublisher, line 274, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module plone.z3cform.layout, line 63, in __call__
  Module plone.z3cform.layout, line 47, in update
  Module plone.dexterity.browser.edit, line 58, in update
  Module plone.z3cform.fieldsets.extensible, line 65, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 22, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module plone.dexterity.browser.edit, line 30, in handleApply
  Module z3c.form.group, line 114, in applyChanges
  Module z3c.form.form, line 51, in applyChanges
  Module senaite.core.z3cform.datamanager, line 36, in set
  Module senaite.core.schema.uidreferencefield, line 211, in set
  Module senaite.core.schema.uidreferencefield, line 225, in unlink_backref
ValueError: Objects in initialization state can not have existing back references!
```

* Check if the object implements IBehavior instead of checking if object