Fix getting values for getProvince and getDistrict (from client) in ARs view
In folderitem from AnalysisRequestView, the client was retrieved by querying
portal_catalog just for getting the province and district, but there weren't
such indexes in that catalog. In addition, the ARs catalog already had those
two indexes, so there was no need to get the client first. Since both fields
were declared in the columns schema, they are now automatically filled by
bikallisting.

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.analysisrequest.analysisrequests, line 1071, in __call__
  Module bika.lims.browser.bika_listing, line 808, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 98, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 289, in render
  Module chameleon.template, line 191, in render
  Module chameleon.template, line 171, in render
  Module 1ee2209cad76db9278cd5726ac4bfad1.py, line 499, in render
  Module cf87da5b091a65499ac2b4dfafb7f66b.py, line 1172, in render_master
  Module cf87da5b091a65499ac2b4dfafb7f66b.py, line 484, in render_content
  Module 1ee2209cad76db9278cd5726ac4bfad1.py, line 429, in __fill_content_core
  Module five.pt.expressions, line 161, in __call__
  Module bika.lims.browser.bika_listing, line 1289, in contents_table
  Module bika.lims.browser.bika_listing, line 1442, in __init__
  Module bika.lims.browser.analysisrequest.analysisrequests, line 782, in folderitems
  Module bika.lims.browser.bika_listing, line 1036, in folderitems
  Module bika.lims.browser.analysisrequest.analysisrequests, line 800, in folderitem
AttributeError: getProvince