Some instances < 1.3.0 does not have unassigned state for analysis wf
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.GenericSetup.tool, line 1053, in manage_doUpgrades
  Module Products.GenericSetup.upgrade, line 166, in doStep
  Module bika.lims.upgrade, line 55, in wrap_func_args
  Module bika.lims.upgrade.v01_03_000, line 102, in upgrade
  Module bika.lims.upgrade.v01_03_000, line 440, in update_workflows
  Module bika.lims.upgrade.v01_03_000, line 673, in get_role_mappings_candidates
  Module bika.lims.upgrade.v01_03_000, line 835, in get_rm_candidates_for_analysisworkfklow
AttributeError: unassigned