Bind the analysis method to the reflex rule object
    Drop down list
    Displayed in rules folder
    setup js

bin/test -v -p -s bika.lims --suite-name='bika.lims.tests' --test='TestReflexRules'
	Test-module import failures:

Module: bika.lims.tests.test_doctests

TypeError: Module bika.lims.tests.test_doctests does not define any tests

Module: bika.lims.tests.test_robot

TypeError: Module bika.lims.tests.test_robot does not define any tests

Running tests at level 1
Running bika.lims.testing.BikaTestingLayer:Functional tests:
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.z2.Startup in 0.165 seconds.
  Set up plone.app.testing.layers.PloneFixture in 4.917 seconds.
  Set up bika.lims.testing.BikaTestLayer in 45.058 seconds.
  Set up bika.lims.testing.BikaTestingLayer:Functional in 0.000 seconds.
  Running:

  Ran 2 tests with 0 failures and 0 errors in 0.804 seconds.
Tearing down left over layers:
  Tear down bika.lims.testing.BikaTestingLayer:Functional in 0.000 seconds.
  Tear down bika.lims.testing.BikaTestLayer in 0.010 seconds.
  Tear down plone.app.testing.layers.PloneFixture in 0.052 seconds.
  Tear down plone.testing.z2.Startup in 0.004 seconds.
  Tear down plone.testing.zca.LayerCleanup in 0.004 seconds.

Test-modules with import problems:
  bika.lims.tests.test_doctests
  bika.lims.tests.test_robot