New Sidebar Navigation (#2835)
* Initial commit

* styles updated

* Sidebar uses uid_catalog

* Updated styles and JS

* Move config to setup

* Show top level items directly

* Styles corrected

* Handle UID catalog brains for path/url calculation

* Refactoring

* Fix sidebar search

* Rebuild JS/CSS

* Make sidebar resizable

* Move sidebar into senaite.core namespace

* Load more button styling

* Load more functionality

* Makde default depth 2

* Handle show_more flag

* Use specific catalog for child searches

* Refactored to ReactJS components

* Fixed build errors

* Skip folders/portal_types in setup

* Added tooltip

* Changelog updated

* Test fixed

* production js

* Mobile sidebar handling

* Whitespace only

* Fix TypeError: Missing.Value is not JSON serializable

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 176, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 385, in publish_module
  Module ZPublisher.WSGIPublisher, line 288, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module senaite.core.browser.viewlets.sidebar, line 179, in __call__
  Module json, line 244, in dumps
  Module json.encoder, line 207, in encode
  Module json.encoder, line 270, in iterencode
  Module json.encoder, line 184, in default
TypeError: Missing.Value is not JSON serializable
```

* Removed inline import

* Combined navigation types

* Removed obsolete registry entry

* Check brains for Missing.Value

* Use skip types instead of display types

* Fixed test

* Skip Attachment type as well

* Removed accessibility attributes

---------

Co-authored-by: Jordi Puiggené <jp@naralabs.com>