Fix analyses results not set after auto import (#1855)
* Refactored auto_import_results view

* Refactoring and docstrings

* Logging

* Add log when file is skipped

* Docstrings

* Write autologs

* Removed old resultsimport

* Allow to manually trigger auto-import

* typo

* Changed text

* fixed condition

* Added test

* Use global variable CR instead of \n

* Changelog updated

* Last "end" tag not needed

* Test auto import log

* Implement IFileUpload in file wrapper

* Fixed import

* Fixed doctests

* Fixed AttributeError when importing QC results

Traceback:

2021-10-13 20:21:21 ERROR senaite.core Traceback (most recent call last):
  File "senaite.core/src/senaite/core/exportimport/auto_import_results.py", line 125, in import_results
    importer.process()
  File "senaite.core/src/senaite/core/exportimport/instruments/resultsimport.py", line 609, in process
    sample_id = analysis.getRequestID()
AttributeError: 'RequestContainer' object has no attribute 'getRequestID

* Fixed doctests (again)

* Avoid that the upload file get deleted when an attachment is created