Migrate Lab Departments to Dexterity (#2471)
* Added DX contents for Departments

* Removed AT type registration

* upgrade step and setuphandlers

* Content migration

* Added controlpanel listing view

* Removed obsolete views

* Refactored controlpanel listing views

* Changed title

* Changelog updated

* Fixed import setup handler

* Fixed doctests

* Removed PDB

* Updated demodata

* Avoid traceback in upgrade step 2525

Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 176, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 385, in publish_module
  Module ZPublisher.WSGIPublisher, line 288, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module Products.GenericSetup.tool, line 1135, in manage_doUpgrades
  Module Products.GenericSetup.upgrade, line 185, in doStep
  Module senaite.core.upgrade.v02_05_000, line 666, in setup_client_landing_page
  Module senaite.core.upgrade, line 39, in wrap_func_args
  Module senaite.core.upgrade.v02_05_000, line 275, in import_registry
  Module Products.GenericSetup.tool, line 375, in runImportStepFromProfile
  Module Products.GenericSetup.tool, line 1323, in _doRunImportStep
   - __traceback_info__: typeinfo
  Module Products.CMFCore.exportimport.typeinfo, line 222, in importTypesTool
  Module Products.GenericSetup.utils, line 933, in importObjects
   - __traceback_info__: portal_types
  Module Products.GenericSetup.utils, line 929, in importObjects
   - __traceback_info__: types/Department
  Module Products.GenericSetup.utils, line 530, in _importBody
  Module Products.CMFCore.exportimport.typeinfo, line 61, in _importNode
  Module Products.GenericSetup.utils, line 762, in _initProperties
ValueError: undefined property 'add_permission'

* Fixed UID catalog not updated

* Typo fixed

* Make 2.5 migrations compatible

* Compatibility with SENAITE IMPRESS

* Re-added decorator

* Remove bika.lims.department.js

* Spelling and i18n

* Setters should not return nothing

* Typo

* Make getter return utf-8 string

* Add getRawManager

* Spelling

* Remove legacy listing for AT departments

* yarn build

* Resolve issue with gaps in id server after import

* Revert "Resolve issue with gaps in id server after import"

This reverts commit 60808167aac327bcc00f431a01aa82bf0bdefbf3.

* Keep idserver unchanged, without gaps

* Make UID catalog a varaibale

* Added flush storage function

* Added an attribute for DepartmentID

* Added schema field properties

---------

Co-authored-by: Jordi Puiggené <jp@naralabs.com>