Analysis workflow refactoring (#1077)
* Refactoring of Analysis submission transition and guard

* Remove unused code

* Ensure integrity of interimfields between Service and Calculation

* Added doctest for submission of results with interim calculation

* Organize imports

* Added doctest for the submission of analyses with dependencies

* Doctest for auto-submit of Worksheet when all analyses are submitted

* Clean imports

* Added doctest for Duplicate analysis submit transition and guard

* Update submit guard for DuplicateAnalysis

* Added test for basic constrictions on DuplicateAnalysis submission

* Added doctest for submission of Duplicates with interims

* Added Doctest for submission of duplicate with interims

* Added doctest for submission of duplicates with dependencies

* Update transition submit and guard for ReferenceAnalysis

* When adding a Reference Analysis to WS, use interims from Service

* Add getDependents() function to return [] in Reference Analysis

Dependents and dependencies are not allowed in Reference Analyses, but
having these functions (returning an empty list) allows the system to
not need to explicitily differentiate between other types of analyses
and those that are reference, reducing the overall complexity.

* Fix typo in WorkflowDuplicateAnalysisSubmit doctest

* Import the whole guards package from analysis in referenceanalysis/guards

* Added doctest re submit transition and guard for Blank analyses

* Added doctest re submit transition/guard for Control analyses

* Always reindex the analysis after submit

* Fix ARAnalysesField doctest

Now, as was stated in the comments of the doctest, getInterimFields()
function from analysis returns the merge of interims set at analysis
level with the interims from the calculation.

* Do not explicility set interims from calculation in References

Since service's getInterimFields() returns the merge of service-specific
interims + calculation's interim fields, there is no need to explicitily
set interims from the calculation to the reference analysis after being
created, cause they have already been set before in function
reference.addReferenceAnalysis(service_uid, ref_type)

* Move the assignment of interims to create_analysis function

* Cleanup imports

* Remove active_only and allowed_transitions from doActionFor

These parameters are not used anywhere and in fact, are harmful

* Remove unnecessary code

WorkflowTool's doActionFor already checks if the instance can be
transitioned based on guards and permissions, so there is no need
to add this additional check (which has a performance hit)

* Better management of reindexing after transition events

* Complexity redux (and doctest) for ObjectRemovedEventHandler (analysis)

* Comment

* Remove unuseful code

The skip thing is already managed by doActionFor and without it, this
handler does not make sense at all.

* First update of workflow for verify transition/guard in analysis

* Added basic test for verify transition/guard

* Added doctest for auto-verification of Worksheets

* Only dependencies are auto-transitioned, not dependents

* Permissions check for WorkflowAnalysisVerify.rst

* Remove permission "Review portal content" from to_be_verified state

* Fix Edit Results permission for submit transition

* Cleanup imports

* Fix permission for submit transition in duplicateanalysis_workflow

* Fix permissions for guard verify and state assigned from reference workflow

* Permission check in doctest for blanks

* Added permission checks in doctest for control analyses

* Cleanup

* Fixed verify guards for reference and duplicate analyses

* Doctest verify transition and guard for duplicates

* Verifier should be able to verify duplicates... but not yet possible

* Remove comment

* Added doctest for control+blank verify action/guard

* Refactor multi-verification of analyses, with multi_verify transition

* Added doctests for multiverification with blanks and controls

* Remove TODOs

* Decouple analysis workflow from AR's sample_received

* Added index isAnalysisRequestReceived in analysis catalog

Allows to filter the analyses depending on if the AnalysisRequest
they are assigned to has been received or not

* Removal of no longer used transitions and states from analysis wf

* Permissions cleanup in analysis_workflow

* Remove analyses not requested state, transition and related code

* Allow/disallow users to submit results for unassigned analyses

* Code redux

* Fix Analysis Request retract test

The test was failing because "submit" transition for "field" analyses
is not allowed anymore, unless the AR/Sample has been sampled (if
workflow_sampling enabled) or the AR has a valid DateSample

* Remove worksheetanalysis_workflow

* Fix DateSampled is not set automatically after sample transition

* Added assign/unassign buttons in WS Add Analyses and WS analyses view

* Revert "Added assign/unassign buttons in WS Add Analyses and WS analyses view"

This reverts commit 7dd1cbcfff065cf4a186b458bb369d85bb9e4e3b.

* Added assign/unassign transition guards for analysis_workflow

* Remove "Cancel and Reinstance" permission from analysis_workflow

Analysis cannot be cancelled, but rejected or retracted

* Bind WS's addAnalysis and removeAnalysis funcs with assign/unassign

* Remove superfluous "assign" transition from ref/dup analyses

Since reference analyses and duplicates can only exist if they are
bound to a Worksheet (and/or to an Instrument for reference analyses),
make the initial state to be assigned. For the same reason, an
"unassigned" reference analysis or duplicate will not be accessible
anywhere anymore, so better to make the "unassign" transition to remove
these analyses from the system. Note that "unassign" transition is
only permitted when the state is "assigned", so there are no results
yet and the removal is safe.

This commit includes some refactoring, improvements and redux of
content.worksheet to make the addition/removal of analyses (and their
counterpart transitions "assign" and "unassign") faster.

* Fix AttributeError: getWorksheetUID in upgrade step 1.3

* Removing a routine analysis from a WS causes the removal of its duplicates

* Unassign analyses causes the removal of their duplicates counterparts

* Log when a duplicate does not have an analysis and on removal

* Allow to pass service objects to addReferenceAnalyses function

The function now can receive either service objects or service uids

* Added assign tests for blanks and controls

* Added rollback_to_receive transition in ar workflow

* Analysis' retract workflow refactoring

* Cleanup imports

* On analysis retraction, ensure dependents are retracted too

* Added rollback_to_open transition in worksheet workflow

* Added scenario in analysis retract doctest for worksheet

* Clean-up

* Remove Retested field from Analysis - RetestedOf instead

Retested field was confusing, if the value for this field was True,
it meant the current analysis was a retest, not the other way round.
This field has been removed and an additional field "RetestedOf" has
been added, as well as a function "isRetest".

Index "getRetested" (FieldIndex) from analysis_catalog has been
replaced by "isRetested" (BooleanIndex). Metadata column "getRetested"
has been replaced by "getRetestedOfUID", that returns the UID of the
retracted analysis the current analysis is a retest of.

* Organize imports of workflow/worksheet/events

* Creation of retests for duplicates via retraction

* Add (not-definitive) entries in CHANGES.rst

* Check if transition is allowed before doActionFor

* Cleanup BeforeTransitionEventHandler

* Action handler pool for recursive transitions was not working

* Make the assignment of Analyses to Worksheet faster

Use ActionHandlerPool to prevent the reindexing of already processed
objects and reindex all them at once.

* Split worksheet's view assign logic to function do_assign

* Fix AttributeError: ActionHandlerPool instance has no attribute 'is_empty'

* Avoid references from the service interims to the calculation interims

* Clarifying comments regarding ActionsPoolHandler

* Creation of retests for blanks and controls via retraction

* Fix WorkflowDuplicateAnalysisAssign test

* Cleanup workflow_script_*

* Analysis reject transition and guard

* Remove unused code

* Fix tests

* Redux getBillableItems from content.analysisrequest

* More redux for getBillableItems and related

* Fix unsupported operand in getBillableItems

* Assigned state icon was not displayed in AR listings

* Decouple cancellation_workflow from Analysis content type

* Remove no longer needed is_active(analysis) checks in guards

* Sort states and transitions (no changes other than sorting)

* Remove re-declared after_cancel in workflow.analysis.events

* Rejection of an analysis causes the removal of its duplicates

* Organize imports and getCurrentStatus -> api.get_review_status

* Always make api.is_active to first check for review_state

* Organize imports

* ActionsHandlerPool improvements

* Redux unassign and unassign action in worksheet

* Check if the action has been processed before isTransitionAllowed

* Clenaup

* Fix upgradestep

* addReferenceAnalyses signature change

* add_duplicate --> add_duplicate_analysis

* Fix publish error