ReferenceWidget does not handle searches with null/None
ast does not convert "null" to python's None and the following
Traceback is thrown:

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.widgets.referencewidget, line 204, in __call__
  Module bika.lims.browser.client.ajax, line 31, in __call__
  Module bika.lims.adapters.referencewidgetvocabulary, line 44, in __call__
  Module ast, line 80, in literal_eval
  Module ast, line 63, in _convert
  Module ast, line 62, in <genexpr>
  Module ast, line 60, in _convert
  Module ast, line 79, in _convert
ValueError: malformed string

ast.literal_eval has been replaced by built-in json.loads, and to
overcome the issue about unicodes:
https://github.com/senaite/senaite.core/issues/443
a function that converts unicodes to strings recursively has been
added, as suggested in the same issue above