Error when an object has no status defined while listing in WS
Happened after creating a ReferenceAnalysis:

1492095243.720.42824301321 http://localhost:8080/Plone/worksheets/WS-003/manage_results
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.worksheet.views.results, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 98, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 261, in render
  Module chameleon.template, line 191, in render
  Module chameleon.template, line 171, in render
  Module e8dd4d0250ff52f7615885d10c907454.py, line 1671, in render
  Module 577340f402cac729036f9610038b788b.py, line 1392, in render_master
  Module 577340f402cac729036f9610038b788b.py, line 559, in render_content
  Module e8dd4d0250ff52f7615885d10c907454.py, line 1563, in __fill_content_core
  Module five.pt.expressions, line 161, in __call__
  Module bika.lims.browser.bika_listing, line 1279, in contents_table
  Module bika.lims.browser.bika_listing, line 1440, in __init__
  Module bika.lims.browser.worksheet.views.analyses, line 75, in folderitems
  Module bika.lims.browser.analyses, line 930, in folderitems
  Module bika.lims.browser.bika_listing, line 937, in folderitems
TypeError: 'Missing.Value' object is not iterable

 - Expression: "view/Analyses/contents_table"
 - Filename:   ... ika/lims/browser/worksheet/views/../templates/results.pt
 - Location:   (line 159: col 33)
 - Source:     ... replace="structure view/Analyses/contents_table"/>
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7f5adb6c3ed0>
               views: <ViewMapper - at 0x7f5adb6c3dd0>
               modules: <instance - at 0x7f5afc518638>
               args: <tuple - at 0x7f5b071aa050>
               here: <ImplicitAcquisitionWrapper WS-003 at 0x7f5aef77ae10>
               user: <ImplicitAcquisitionWrapper - at 0x7f5aef63dc30>
               nothing: <NoneType - at 0x7ab150>
               target_language: <NoneType - at 0x7ab150>
               translate: <function translate at 0x7f5adbf5fb90>
               container: <ImplicitAcquisitionWrapper WS-003 at 0x7f5aef77ae10>
               request: <instance - at 0x7f5adbe0c8c0>
               wrapped_repeat: <SafeMapping - at 0x7f5adbffd838>
               traverse_subpath: <list - at 0x7f5adbe581b8>
               default: <object - at 0x7f5b07180c40>
               loop: {...} (3)
               context: <ImplicitAcquisitionWrapper WS-003 at 0x7f5aef77ae10>
               view: <ManageResultsView manage_results at 0x7f5adbff1f10>
               root: <ImplicitAcquisitionWrapper Zope at 0x7f5aef76bb90>
               options: {...} (0)
               last_uid: ba7e114944e543dab76c636ac942059c