Generate unique ID for DX types on object creation (#2372)
* Moved IDServer to senaite.core

* Imports updated

* Allow ID generation before object is created

* Updated imports

* Fixed test

* Import updated

* Backwards compatibility

* Refactored API create for DX contents

* Fixed behaviors

* Added default name chooser fallback

* Make test pass

* Removed unused import

* Fixed test

* Fixed import in test

* Use api.create in doctest

* Handle AT and DX types

* Removed test

* Removed unused code

* Comment only

* Skip unindexing

* Added upgrade step

* Fixed catalog in listing

* Register for contentish and folderish objects

* Skip indexing if object in TempFolder

* Make adapter more specific than the default registration

* Changelog updated

* BBB IIdServerVariables moved to senaite.core.interfaces

* BBB IIdServerTypeID moved to senaite.core.interfaces

* Fix traceback for AT's without catalog assigned by default

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 176, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 385, in publish_module
  Module ZPublisher.WSGIPublisher, line 288, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module Products.CMFPlone.controlpanel.browser.quickinstaller, line 666, in __call__
  Module Products.CMFPlone.controlpanel.browser.quickinstaller, line 399, in upgrade_product
  Module Products.GenericSetup.tool, line 1202, in upgradeProfile
  Module Products.GenericSetup.upgrade, line 185, in doStep
  Module senaite.core.upgrade, line 41, in wrap_func_args
  Module zope.event, line 33, in notify
  Module zope.component.event, line 27, in dispatch
  Module zope.component._api, line 134, in subscribers
  Module zope.interface.registry, line 448, in subscribers
  Module zope.interface.adapter, line 899, in subscribers
  Module senaite.storage.subscribers.upgrade, line 33, in afterUpgradeStepHandler
  Module senaite.storage.setuphandlers, line 222, in post_install
  Module senaite.storage.setuphandlers, line 316, in migrate_storage_locations
  Module bika.lims.api, line 859, in search
  Module Products.CMFPlone.CatalogTool, line 440, in searchResults
  Module Products.CMFCore.indexing, line 97, in processQueue
  Module Products.CMFCore.indexing, line 227, in process
  Module senaite.core.patches.catalog, line 110, in portal_catalog_reindex
  Module senaite.core.patches.catalog, line 93, in in_portal_catalog
TypeError: argument of type 'NoneType' is not iterable
```

---------

Co-authored-by: Jordi Puiggené <jp@naralabs.com>