Release 1.2.5 (180505)
Squashed commit of the following:

commit 080ebdb93e2b144a0accd8cca0e88e6d60b163f0
Author: Jordi Puiggené <jpuiggene@naralabs.com>
Date:   Sat May 5 12:19:51 2018 +0200

    Update release notes

commit c9f0c6aa6aca8c8b3bbb66ded2dfca6049317a56
Author: Jordi Puiggené <jpuiggene@naralabs.com>
Date:   Sat May 5 12:11:21 2018 +0200

    ValueError: substring not found in write_contributions

commit 8a301f6fa98ab3904d5b2dfe907411e30222f20a
Author: Jordi Puiggené <jpuiggene@naralabs.com>
Date:   Sat May 5 11:42:57 2018 +0200

    Cleanup CHANGES.rst for v1.2.5