Fix error when creating a partition as analyst user (#1525)
* Fix error when creating a partition as analyst user

Analyst user was allowed to create partitions because the 'create_partition'
guard was governed by permission "Edit Results" and the permission required for
partition magic view was "ManageAnalysisRequests". Nevertheless, analysts do not
have view permissions for some setup objects (like SampleType), so the system
was throwing an exception after pressing the button "Create Partitions" from
partition magiv view:

```
Traceback (innermost last):
Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module bika.lims.browser.partition_magic, line 97, in call
Module bika.lims.utils.analysisrequest, line 480, in create_partition
Module bika.lims.utils.analysisrequest, line 87, in create_analysisrequest
Module Products.Archetypes.BaseObject, line 636, in processForm
Module bika.lims.content.analysisrequest, line 1420, in _renameAfterCreation
Module bika.lims.idserver, line 518, in renameAfterCreation
Module bika.lims.idserver, line 462, in generateUniqueId
Module bika.lims.idserver, line 227, in get_variables
AttributeError: 'NoneType' object has no attribute 'getPrefix'
```

This commit makes the "create_partition" transition, and the partition magic
view to rely on permission "senaite.core: Add AnalysisRequest", so the
transition is not longer available to analyst, and even if he/she tries to
access manually to partition magic view, the system will display an
"Insufficient privileges" message.

* Do not allow analysts to copy samples