Fix TypeError (setRequestID, unexpected keyword argument) on AR Creation (#334)
* Added 'Supervisor' field to laboratory.

* setRequestId has unused **kwargs now to avoid traceback.

* Changes log.

* Updated PR name.