Error while listing analyses in Analysis Request details view
The index sortable_title is not available in bika_analysis_catalog, so the
following error is rised in AR's detail view:

http://localhost:8080/Plone/clients/client-1/AP-0001-R01/base_view
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.health.browser.analysisrequest.view, line 17, in __call__
  Module bika.lims.browser.analysisrequest.view, line 115, in __call__
  Module bika.lims.browser.bika_listing, line 1279, in contents_table
  Module bika.lims.browser.bika_listing, line 1440, in __init__
  Module bika.lims.browser.analyses, line 1088, in folderitems
  Module bika.lims.browser.analyses, line 930, in folderitems
  Module bika.lims.browser.bika_listing, line 912, in folderitems
  Module Products.CMFPlone.CatalogTool, line 389, in searchResults
  Module Products.ZCatalog.ZCatalog, line 604, in searchResults
  Module Products.ZCatalog.Catalog, line 916, in searchResults
  Module Products.ZCatalog.Catalog, line 889, in _getSortIndex
CatalogError: Unknown sort_on index (sortable_title)