Fix error while creating a Reference Analysis
Some fields from ReferenceAnalysis object are indexed at creation time,
but its value depends on the Service associated to the ReferenceAnalysis.
The Service was assigned to the ReferenceAnalysis after its creation, so
exceptions like the one below were raised while _createObjectByType:

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.worksheet.views.add_blank, line 56, in __call__
  Module bika.lims.content.worksheet, line 309, in addReferences
  Module bika.lims.content.referencesample, line 323, in addReferenceAnalysis
  Module Products.CMFPlone.utils, line 333, in _createObjectByType
  Module Products.CMFCore.TypesTool, line 559, in _constructInstance
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module Products.CMFCore.CMFCatalogAware, line 262, in handleContentishEvent
  Module Products.CMFCore.CMFCatalogAware, line 188, in notifyWorkflowCreated
  Module Products.CMFCore.WorkflowTool, line 289, in notifyCreated
  Module Products.CMFCore.WorkflowTool, line 635, in _reindexWorkflowVariables
  Module Products.Archetypes.CatalogMultiplex, line 118, in reindexObject
  Module Products.CMFPlone.CatalogTool, line 349, in catalog_object
  Module Products.ZCatalog.ZCatalog, line 476, in catalog_object
  Module Products.ZCatalog.Catalog, line 334, in catalogObject
  Module Products.ZCatalog.Catalog, line 284, in updateMetadata
  Module Products.ZCatalog.Catalog, line 410, in recordify
  Module bika.lims.content.referenceanalysis, line 261, in isInstrumentValid
AttributeError: 'NoneType' object has no attribute 'getInstrumentEntryOfResults'