Error when exporting Worksheets list with senaite.exporter
`senaite.exporter` directly calls to filderitems function from the view
that implements BikaListing. Thus, if some variables that haven't been
initialized before are useed there, a Traceback is rised:

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module senaite.exporter.list_exporters, line 48, in __call__
  Module senaite.exporter.list_exporters, line 131, in export_to_list
  Module senaite.exporter.list_exporters, line 152, in get_items
  Module bika.lims.browser.worksheet.views.folder, line 326, in folderitems
  Module bika.lims.browser.bika_listing, line 932, in folderitems
  Module bika.lims.browser.worksheet.views.folder, line 255, in isItemAllowed
AttributeError: 'FolderView' object has no attribute 'selected_state'

As a good practice, class variables should always be initialized in the
class constructor __init__, and this commit does it. As a colateral
effect, exporter works without rising any error.