Migrate Worksheet to DX (#2805)
* Migrate AT Worksheet -> DX

* add step to upgrade configure

* fix and refactoring

* fix linter warning without tests

* fix lint

* fix lint and update demodata archive

* fix lint (

* bika setup -> senaite registry -> senaite setup; tests fixed.

* fix lint: remove unused imported

* fix migrate step

* fix lint: remove unused imported

* fix upgrade step for remarks; add widget for remarks field

* rename package worksheets -> worksheet; optimize imports blocks.

* fix for printview page

* intermediate commit after review

* fix permission

* fix check get_user

* fix vocabulary for instrument field

* copy settings from bika_setup to senaitesetup into upgrade step

* change structure folders

* fix import views

* fix include package into configure

* change template for folder view

* fix after review

* remove unused imports

* fix test for removed workflow status 'rejected' for ws

* change condition for select view

* change upgrade step: first rename old folder

* fix worksheet layouts vocabulary

* remove unused imports

* Fix TypeError: getAnalyses() got an unexpected keyword argument 'full_objects'

Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 176, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 385, in publish_module
  Module ZPublisher.WSGIPublisher, line 288, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module senaite.core.browser.worksheets.worksheet.manage_results, line 84, in __call__
  Module Products.Five.browser.pagetemplatefile, line 126, in __call__
  Module Products.Five.browser.pagetemplatefile, line 61, in __call__
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 378, in __call__
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 302, in render
  Module chameleon.template, line 215, in render
  Module chameleon.template, line 192, in render
  Module 1ae0dde3615a24c131608fdf7fab4250, line 1816, in render
  Module 3b4abe6abe95c5b8cf33b79d89b266cc, line 1428, in render_master
  Module 3b4abe6abe95c5b8cf33b79d89b266cc, line 407, in render_content
  Module 1ae0dde3615a24c131608fdf7fab4250, line 1709, in __fill_content_core
  Module zope.tales.pythonexpr, line 73, in __call__
   - __traceback_info__: (view.contents_table())
  Module <string>, line 1, in <module>
  Module senaite.core.browser.worksheets.worksheet.manage_results, line 94, in contents_table
  Module senaite.core.browser.worksheets.worksheet.analyses_listing, line 150, in before_render
  Module senaite.core.browser.worksheets.worksheet.analyses_listing, line 165, in enable_remarks
  Module senaite.core.browser.worksheets.worksheet.analyses_listing, line 201, in show_analysis_remarks_transition
  Module senaite.core.browser.worksheets.worksheet.analyses_listing, line 211, in get_analyses
TypeError: getAnalyses() got an unexpected keyword argument 'full_objects'

---------

Co-authored-by: Ramon Bartl <rb@ridingbytes.com>
Co-authored-by: Jordi Puiggené <jp@naralabs.com>