Fix error when using obj.getDepartmentUIDs(), cause obj is a brain
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.bika_listing, line 804, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 98, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 276, in render
  Module chameleon.template, line 191, in render
  Module chameleon.template, line 171, in render
  Module b3db0640eb90d28b2c249699f57068cc.py, line 846, in render
  Module 3cd558b0ecf4f5881bee7d47c02abbda.py, line 1420, in render_master
  Module 3cd558b0ecf4f5881bee7d47c02abbda.py, line 578, in render_content
  Module b3db0640eb90d28b2c249699f57068cc.py, line 812, in __fill_content_core
  Module five.pt.expressions, line 161, in __call__
  Module bika.lims.browser.bika_listing, line 1279, in contents_table
  Module bika.lims.browser.bika_listing, line 1440, in __init__
  Module bika.lims.browser.worksheet.views.folder, line 327, in folderitems
  Module bika.lims.browser.bika_listing, line 932, in folderitems
  Module bika.lims.browser.worksheet.views.folder, line 259, in isItemAllowed
TypeError: 'list' object is not callable

 - Expression: "view/contents_table"
 - Filename:   ... /lims/browser/worksheet/views/../templates/worksheets.pt
 - Location:   (line 89: col 31)
 - Source:     tal:content="structure view/contents_table"/>
                                      ^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7f7f04839090>
               views: <ViewMapper - at 0x7f7f0c583090>
               modules: <instance - at 0x7f7f244511b8>
               args: <tuple - at 0x7f7f2f289050>
               here: <ImplicitAcquisitionWrapper worksheets at 0x7f7f0c526820>
               user: <ImplicitAcquisitionWrapper - at 0x7f7f0c04fe10>
               nothing: <NoneType - at 0x7b1070>
               translate: <function translate at 0x7f7f047c9c80>
               container: <ImplicitAcquisitionWrapper worksheets at 0x7f7f0c526820>
               request: <instance - at 0x7f7f0c04bf80>
               wrapped_repeat: <SafeMapping - at 0x7f7f149e0838>
               traverse_subpath: <list - at 0x7f7f0c8c71b8>
               default: <object - at 0x7f7f2f25fc30>
               loop: {...} (3)
               context: <ImplicitAcquisitionWrapper worksheets at 0x7f7f0c526820>
               view: <FolderView base_view at 0x7f7f0c3aca50>
               target_language: <NoneType - at 0x7b1070>
               root: <ImplicitAcquisitionWrapper Zope at 0x7f7efb755d70>
               options: {...} (0)