Compliance of Analyses from Samples with Specification (#1506)
* Better handling of Specification + ResultsRange in Sample

* Added viewlet for Specification vs Results Range differences

* Viewlet for when field change is populated to partitions

* Added IAnalysisRequestWithPartitions interface

* Store ResultsRange directly to Analyses

* Typo

* Add uid property in ResultsRangeDict

* When a new Specification is applied, apply changes to analyses too

* Refactor create_analysisrequest function

* Refactor aranalysesfield

* SpecificationsField must return empty dict instead of None

* When Specification's results ranges are changed, reapply to Sample

Analyses from the sample will use the results ranges set initially, so
if the Specification object is change afterwards, this will not have any
impact to previously created samples and tests

* Compare with previous snapshot, not with the first one

create_analysisrequest has been refactored so the analyses are not passed in
through values['Analyses'] anymore, rather they are set manually afterwards.
This prevents a lot of inconsistencies and makes the creation cleaner.
As a result, the first version of a Sample won't never contain analyses.

* Sample's ResultsRange does not get updated when applied to single analysis

* Some functions from aranalysesfield return a list now

* Fix NameError: global name 'api' is not defined

* Ensure ResultsRangeField always return a copy

* Added doctest

* More rules in doctest

* Ensure no duplicates are stored in Sample's ResultsRange

* More test use cases

* Populate Sample ResultsRange settings to partitions

* Use case for when Partitions are used with specs assignment

* aranalysesfield clean-up

* Fix possible recursion error when fetching calculation dependencies

* Remove unnecessary stuff from the doctest

* Make setAnalyses from ARAnalysesField to not return anything

* SpecificationsField -> ResultsRangesField

* A bit of clean-up

* Ensure ResultsRange value is always stored as a built-in dict

* Assume that an analysis is added w/o specs, it does not break compliance

* Remove getResultsRangeDict from analysisspecs

* Populate Sample's ResultsRanges to Partitions on creation

* Add some comments

* Revisit InternalUse

* Apply result ranges to analyses that are not yet submitted only

* Viewlet for when analyses with non-compliant ranges

* Fix unexpected keyword argument 'remove_primary_analyses'

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.partition_magic, line 100, in __call__
TypeError: create_partition() got an unexpected keyword argument 'remove_primary_analyses'

* Better messages

* Emphasize analyses with non-compliant ranges in analyses listing

* Fix test

* Changelog

* Remove unnecessary code

* Sample can have multiple analyses with same Keyword

* Skip invalid/cancelled analyses while setting results range

* Always store results ranges as str

* Omit services not present in sample when checking if specs is out-of-date

* Added viewlet in Sample for when dynamic spec is assigned

* Remove unnecessary code

* Fix test

* Upgrade step

* Bad comment

* Better equals for ResultRangeDict

* specifications --> results_ranges

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.analysisrequest.add2, line 66, in decorator
  Module bika.lims.browser.analysisrequest.add2, line 734, in __call__
  Module bika.lims.browser.analysisrequest.add2, line 1673, in ajax_submit
TypeError: create_analysisrequest() got an unexpected keyword argument
'specifications'

* Remove internal imports of ResultsRangeDict

* Non-supported "error" subfield is imported in specs through setup data

* Revert "Remove internal imports of ResultsRangeDict"

This reverts commit 91467bcd52d3fa15c9e14500ef5b7bc4e136d39c.

* Removed "primary bound" viewlet

This change displays an icon in the header table next to the fields that
have the `primary_bound` set to `True`.

* Commit changes during the migration step to free some memory

* Minor cleanup and PEP8

* Preserve the sample specification if no changes are done

* Do not re-assign the Specification unless different value

The aim is to preserve the result ranges manually set to analyses
and to the Sample itself when the Save button is pressed in the
Sample view while the user has not changed the value for Specification

* Remove unnecessary log.error

Co-authored-by: Ramon Bartl <rb@ridingbytes.com>