Fix reference widget lookups (#2384)
* Lookup default catalog with the API

* Compatibilty with new reference widget

* Fix description and query

* Compatibility with new reference widget

* Added portal_type to query

* Additional CSS class

* Handle select/deselect events in editform

* Ensure portal_type query

* Refactored labcontact schema

* Fix dynamic default department

* Handle referencefield select/deselect

* Generated Production JS

* Description improved

* Imports sorted

* Compatibility with new reference widget

* Also allow supplier contacts

* Compatibility with new reference widget for analysis category

* Compatibility with new reference widget

* Make flake8 happy

* Removed dead code

* Compatibility with new reference widget

* Compatibility with new reference widget

* Compatibility with new reference widget

* Compatibility with new reference widget

* Compatibility with new reference widget

* Compatibility with new reference widget

* Compatibility with new reference widget

* Changed to selection widget

* Compatibility with new reference widget

* Imports sorted

* Compatibility with new reference widget

* Minor change

* Compatibility with new reference widget

* Compatibility with new reference widget

* Compatibility with new reference widget

* Compatibility with new reference widget

* Compatibility with new reference widget

* Compatibility with new reference widget

* Compatibility with new reference widget

* compatibility with new reference widget

* Compatibility with new reference widget

* Compatibility with new reference widget

* Compatibility with new reference widget

* Compatibility with new reference widget

* compatibility with new reference widget

* Disallow removal if readonly

* Compatibility with new reference widget

* Compatibility with new reference sample

* Minor change

* Compatibility with new reference widget

* compatibility with new reference widget

* Make allowed types a tuple

* compatibility with new reference widget

* Compatibility with new reference widget

* compatibility with new reference widget

* compatibility with new reference widget

* Compatibility with new reference widget

* Compatibility with new reference widget

* Avoid acquisition in lookup

* compatibility with new reference widget

* Compatibility with new refrence widget

* compatibility with new reference widget

* Compatibility with new reference widget

* Compatibility with new reference widget

* Changelog updated

* Removed unused import

* Use title instead of fullname

* Handle empty value lookups

* Fix batch referencewidget error while searching for Batch

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 176, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 385, in publish_module
  Module ZPublisher.WSGIPublisher, line 288, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module senaite.core.browser.widgets.referencewidget_search, line 29, in __call__
  Module senaite.core.browser.widgets.referencewidget_search, line 73, in search
  Module senaite.core.browser.widgets.referencewidget_search, line 47, in get_ref_data
  Module senaite.core.adapters.referencewidget.dataproviders, line 105, in to_dict
  Module senaite.core.adapters.referencewidget.dataproviders, line 50, in lookup
  Module bika.lims.content.batch, line 260, in getProgress
  Module bika.lims.content.batch, line 242, in getAnalysisRequests
  Module bika.lims.content.batch, line 234, in getAnalysisRequestsBrains
  Module Products.CMFCore.utils, line 13, in check_getToolByName
  Module Products.CMFCore.utils, line 139, in getToolByName
AttributeError: senaite_catalog_sample
```

* Fix old-style referencewidget for SampleContainer in SampleType

* Remove unnecessary showOn=True

* Fix AttributeError when looking for PrimaryAnalysisRequest objects

Some functions from content types my rely on `aq_parent` (e.g objects that
implement `IClientAware`). Current decorator unwraps acquisition from the
object to extract data from, so functions that use acquisition fail

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 176, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 385, in publish_module
  Module ZPublisher.WSGIPublisher, line 288, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module senaite.core.browser.widgets.referencewidget_search, line 29, in __call__
  Module senaite.core.browser.widgets.referencewidget_search, line 73, in search
  Module senaite.core.browser.widgets.referencewidget_search, line 47, in get_ref_data
  Module senaite.core.adapters.referencewidget.dataproviders, line 95, in to_dict
  Module senaite.core.adapters.referencewidget.dataproviders, line 64, in get_base_info
  Module senaite.core.adapters.referencewidget.dataproviders, line 50, in lookup
  Module bika.lims.content.analysisrequest, line 1466, in Description
AttributeError: 'AnalysisRequest' object has no attribute 'aq_parent'
```

* Make lint happy

* Display the batch subgroup Title instead of the Id

* Avoid waking up the object

* Don't wake up the object for Missing.Value

* No getPrefix in columns

* Cleanup

* Added a todo for a fix

---------

Co-authored-by: Jordi Puiggené <jp@naralabs.com>